# default settings
defaults:
  - _self_
  - override hydra/job_logging: custom
  - override hydra/hydra_logging: colorlog

# paths
data_root: './data'
checkpoint_dir: './checkpoints/${model}'
checkpoint_path: '${checkpoint_dir}/checkpoint_best.pth'
train_image_dir: '${data_root}/patches_img_trainset'
train_mask_dir: '${data_root}/patches_mask_trainset'
test_image_dir: '${data_root}/patches_img_testset'
test_mask_dir: '${data_root}/patches_mask_testset'
result_dir: './outputs/${model}'

# architecture
in_channel: 3
model: 'unet'
encoder: 'resnet34'
encoder_weights: 'imagenet'
classes: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
activation: 'softmax2d'  # could be None for logits or 'softmax2d' for multiclass segmentation
device: 'cuda'

# training & testing
warm: false
freeze_encoder: false
gpu_ids: [0, 1, 2, 3]
num_epochs: 50
lr: 0.0001
weight_decay: 0.00001
batch_size: 256
num_workers: 11
num_examples: 1000
seed: 1117

# hydra settings
hydra:
  run:
    dir: './outputs'
  verbose: false
