# default settings
defaults:
  - _self_
  - override hydra/job_logging: custom
  - override hydra/hydra_logging: colorlog

# paths
run_suffix: ''
data_root: '.'

checkpoint_dir: './checkpoints/${model}${run_suffix}'
checkpoint_path: '${checkpoint_dir}/checkpoint_99.pth'

# training files
train_image_dir: '${data_root}/mines_train/patches'
train_mask_dir: '${data_root}/mines_train/masks/patches'

# validation files
valid_image_dir: '${data_root}/mines_train/patches'
valid_mask_dir: '${data_root}/mines_train/masks/patches'

# test files
test_image_dir: '${data_root}/mines_test/patches'
test_mask_dir: '${data_root}/mines_test/masks/patches'

# to-predict-files
pred_image_dir: '${data_root}/CHILE/patches'
pred_mask_dir: ''

# output folder
result_dir: './outputs/${model}${run_suffix}'
# result_dir: './outputs/chile_pred/'

# architecture
in_channel: 3
model: 'unet'
encoder: 'resnet50'               # https://smp.readthedocs.io/en/latest/encoders.html
encoder_weights: 'imagenet'
# classes: ['-', 'lh', 'mf', 'op', 'pp', 'sy', 'tsf', 'wr']
classes: ['bg', 'ms']
# remapping: {'0':0, '3':1, '4':2, '5':3, '6':4, '7':5, '8':6, '9':7}
remapping: null
activation: null                  # null for logits (softmax to be computed in loss)

# training & testing
use_cuda: true
warm: true                       # warm start from checkpoint
warm_optimizer: true              # load optimizer from checkpoint if available
warm_scheduler: true              # load scheduler from checkpoint if available
freeze_encoder: false
gpu_ids: [8]
num_epochs: 100
weight_decay: 0.00001
batch_size: 8
num_workers: 16
num_examples: 1000000
seed: 1117
loss: ce                          # ce, dice, focal
lr: 1e-3
scheduler:
  base_lr: 1e-4
  max_lr: ${lr}
  step_size_up: 2000
  mode: triangular2

# wandb
wandb: false
wandb_entity: zhaiyu
wandb_project: mineseg
wandb_dir: './outputs'

# hydra settings
hydra:
  run:
    dir: './outputs'
  verbose: false
